/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary:                    '#5744cf',
        secondary:                  '#006a65',
        tertiary:                   '#864f00',
        background:                 '#f7f9fb',
        surface:                    '#f7f9fb',
        'surface-bright':           '#f7f9fb',
        'surface-dim':              '#d8dadc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f2f4f6',
        'surface-container':        '#eceef0',
        'surface-container-high':   '#e6e8ea',
        'surface-container-highest':'#e0e3e5',
        'surface-variant':          '#e0e3e5',
        'surface-tint':             '#5947d1',
        'on-surface':               '#191c1e',
        'on-surface-variant':       '#474554',
        'on-background':            '#191c1e',
        'on-primary':               '#ffffff',
        'on-primary-container':     '#fffbff',
        'on-primary-fixed':         '#170065',
        'on-primary-fixed-variant': '#412ab9',
        'on-secondary':             '#ffffff',
        'on-secondary-container':   '#006f69',
        'on-secondary-fixed':       '#00201e',
        'on-secondary-fixed-variant':'#00504c',
        'on-tertiary':              '#ffffff',
        'on-tertiary-container':    '#fffbff',
        'on-tertiary-fixed':        '#2c1600',
        'on-tertiary-fixed-variant':'#683c00',
        'on-error':                 '#ffffff',
        'on-error-container':       '#93000a',
        'primary-container':        '#705fe9',
        'primary-fixed':            '#e4dfff',
        'primary-fixed-dim':        '#c7bfff',
        'secondary-container':      '#76f3ea',
        'secondary-fixed':          '#79f6ed',
        'secondary-fixed-dim':      '#59dad1',
        'tertiary-container':       '#a86500',
        'tertiary-fixed':           '#ffdcbd',
        'tertiary-fixed-dim':       '#ffb86c',
        'error':                    '#ba1a1a',
        'error-container':          '#ffdad6',
        outline:                    '#787586',
        'outline-variant':          '#c8c4d6',
        'inverse-surface':          '#2d3133',
        'inverse-on-surface':       '#eff1f3',
        'inverse-primary':          '#c7bfff',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
        display:  ['"Plus Jakarta Sans"', 'sans-serif'],
        mono:     ['"Courier New"', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:      '0.375rem',
        md:      '0.5rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}